language: "php"

php:
  - "7.1.18"
  - "7.2.17"
  - "7.3"

before_install:
  - '#### Installing Phive ####'
  - wget https://phar.io/releases/phive.phar
  - wget https://phar.io/releases/phive.phar.asc
  - gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x9B2D5D79
  - gpg --verify phive.phar.asc phive.phar
  - chmod +x phive.phar
  - sudo mv phive.phar /usr/bin/phive
  - phive version

install:
  - '#### Installing Phive dependencies ####'
  - phive --no-progress install --force-accept-unsigned --trust-gpg-keys 4AA394086372C20A,8E730BA25823D8B5,2420BAE0A3BE25C6,31C7E470E2138192
  - '#### Project setup ####'
  - bin/phing setup

before_script:
  - bin/phing cc:before-build

script:
  - bin/phing qa

after_script:
  - bin/phing cc:after-build

cache:
  directories:
    - $HOME/.cache/composer
    - $HOME/.phive
    - $HOME/.gnupg
